[tool.isort]
line_length = 119
force_grid_wrap = 0
multi_line_output = 3
lines_after_imports = 2
use_parentheses = true
include_trailing_comma = true
ensure_newline_before_comments = true
skip_glob = [".git", ".idea", ".vscode", "logs/"]

[tool.black]
line_length = 119
